### ISSUE TITLE
Roadmap to v0.1.0

### ISSUE THREAD

**Issue by monoand6** [monoand6/web3cat#1]
## Features

- [x] Chainlink price feeds
- [x] Price feeds on charts
- [x] Eth balances  
- [x] Portfolio views
- [x] Env variable for cache_path and grid
- [x] Blocks tests with mocks
- [x] Handle empty df corner case
- [x] Edge cases for out of bounds prices and balances
- [x] Plurals to singulars
- [x] Docs + examples
- [x] Jupyter books on coderesearch
- [x] Consider refining grid to 100 blocks
- [x] Check linters, etc.
- [x] CI
- [x] Publish
